const ScreenNames = {
  AuthLoading: "AuthLoading",
  Login: "Login",
  IntroCreateAccount: "IntroCreateAccount",
  CreateAccount: "CreateAccount",
  IntroCreateWallet: "IntroCreateWallet",
  CreateWallet: "CreateWallet",
  CreateWalletStarted: "CreateWalletStarted",
  SeedPhrase: "SeedPhrase",
  TermsPolicy: "TermsPolicy",
  ImportWallet: "ImportWallet",
  ImportMultiCoinWallet: "ImportMultiCoinWallet",
  ImportClassicWallet: "ImportClassicWallet",
  ProtectWallet: "ProtectWallet",
  TabNav: "TabNav",
  Dashboard: "Dashboard",
  DApps: "DApps",
  Notifications: "Notifications",
  Setting: "Setting",
  NDAUDetail: "NDAUDetail",
  ERCDetail: "ERCDetail",
  SwitchWallet: "SwitchWallet",
  Send: "Send",
  AddNdauAccount: "AddNdauAccount",
  Receive: "Receive",
  ConvertNdauToNpay: "ConvertNdauToNpay",
  LockPeriod: "LockPeriod",
  EAIDestination: "EAIDestination",
  SelectNDAU: "SelectNDAU",
  Transactions: 'Transactions',
  TransactionDetail: "TransactionDetail",
  Scanner: "Scanner",
  EditWallet: "EditWallet",
  WalletConnect: "WalletConnect",
  Environments: "Environments",
  ContactSupport: "ContactSupport",
  NFTList: "NFTList",
  NFTDetail: "NFTDetail"
}

export { ScreenNames }